version: '3'
services:
    rsshub:
        build: .
        image: xuanqb/rsshub
        restart: unless-stopped
        ports:
            - 1200:1200
        environment:
            NODE_ENV: production
        container_name: rsshub
        
